management:
  context-path: /manage
spring:
  jpa:
    hibernate:
      ddl-auto: validate
liquibase:
  change-log: classpath:/liquibase/master.xml
authentication:
    oauth:
        clientId: qpqapp
        secret: mySecretOAuthSecret
        tokenValidityInSeconds: 1800
        rememberMeKey: qpqsecurekey
---
spring:
  profiles: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/qpq
    username: postgres
    password: sopra*
    dataSourceClassName: org.postgresql.ds.PGSimpleDataSource