app:
  name: ${project.name}
  description: ${project.description}
  version: ${project.version}
  contact: http://www.github.com/jntakpe/qpq
  license: MIT
  licenseUrl: http://opensource.org/licenses/MIT
management:
  context-path: /manage
spring:
  jpa:
    openInView: false
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.cache.use_second_level_cache: true
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: true
      hibernate.format_sql: true
      hibernate.cache.region.factory_class: com.github.jntakpe.qpq.config.HibernateRegionCacheConfig
      hibernate.cache.use_minimal_puts: false
      hibernate.cache.hazelcast.use_lite_member: true
liquibase:
  change-log: classpath:/liquibase/master.xml
cache:
  port: 5701
  backupCount: 0
  evictionPolicy: LRU
  evictionPercentage: 25
  timeToLive: 3600
authentication:
    oauth:
        clientId: qpqapp
        secret: mySecretOAuthSecret
        tokenValidityInSeconds: 1800
        rememberMeKey: qpqsecurekey
---
spring:
  profiles: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/qpq
    username: postgres
    password: sopra*
    driverClassName: org.postgresql.Driver