app:
  name: ${project.name}
  description: ${project.description}
  version: ${project.version}
  contact: http://www.github.com/jntakpe/qpq
  license: MIT
  licenseUrl: http://opensource.org/licenses/MIT
management:
  context-path: /manage
spring:
  jpa:
    hibernate:
      ddl-auto: validate
liquibase:
  change-log: classpath:/liquibase/master.xml
cache:
  port: 5701
  backupCount: 0
  evictionPolicy: LRU
  evictionPercentage: 25
  timeToLive: 3600
authentication:
    oauth:
        clientId: qpqapp
        secret: mySecretOAuthSecret
        tokenValidityInSeconds: 1800
        rememberMeKey: qpqsecurekey
---
spring:
  profiles: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/qpq
    username: postgres
    password: sopra*
    driverClassName: org.postgresql.Driver